import type { Metadata } from "next";
import { Lexend } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { UserProvider } from "@/contexts/UserContext";
import AutoLogout from "@/components/AutoLogout";
import { User, Mail, Briefcase, Calendar } from "lucide-react";

const lexend = Lexend({
  variable: "--font-lexend",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Evalus - Innovation Meets Evaluation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lexend.variable} antialiased font-main`}>
        <UserProvider>
          {<AutoLogout />}
          {children}
        </UserProvider>
        <Toaster />
      </body>
    </html>
  );
}
